const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const menu=$('.menu'),nav=$('.nav');menu.onclick=()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))};$$('.nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
let lang=localStorage.getItem('lang')||'en';const langBtn=$('#langBtn');function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$$('[data-en]').forEach(el=>el.textContent=el.dataset[lang]);langBtn.textContent=lang==='en'?'عربي':'EN';localStorage.setItem('lang',lang);startTyping()}langBtn.onclick=()=>{lang=lang==='en'?'ar':'en';applyLang()};
const themeBtn=$('#themeBtn');if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark');themeBtn.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')};
let typeTimer;function startTyping(){clearInterval(typeTimer);const words=lang==='ar'?['باحثة ذكاء اصطناعي','متخصصة تقنية معلومات','محللة بيانات','معلّمة ومدرّبة STEM']:['AI Researcher','IT Specialist','Data Analyst','STEM Educator'];let wi=0,ci=0,deleting=false;const el=$('#typed');el.textContent='';typeTimer=setInterval(()=>{const w=words[wi];el.textContent=deleting?w.slice(0,--ci):w.slice(0,++ci);if(!deleting&&ci===w.length){deleting=true;clearInterval(typeTimer);setTimeout(startTyping,1100)}else if(deleting&&ci===0){deleting=false;wi=(wi+1)%words.length}},80)}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.classList.contains('numbers'))animateCounters();observer.unobserve(e.target)}}),{threshold:.14});$$('.reveal').forEach(e=>observer.observe(e));
let counted=false;function animateCounters(){if(counted)return;counted=true;$$('.counter').forEach(el=>{const target=+el.dataset.target,duration=1600,start=performance.now();function step(t){const p=Math.min((t-start)/duration,1),val=Math.floor(target*(1-Math.pow(1-p,3)));el.textContent=target>999?val.toLocaleString():val+(target===6?'+':'');if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step)})}
const modal=$('#researchModal'),open=$('#openResearch'),close=$('.modal-close');function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}open.onclick=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');close.focus()};close.onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const topBtn=$('.to-top');window.addEventListener('scroll',()=>topBtn.classList.toggle('show',scrollY>600));topBtn.onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#year').textContent=new Date().getFullYear();applyLang();
